name: memory
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flip_card: ^0.7.0
  file_picker: ^5.3.2
  excel: ^2.0.0-null-safety-3
  sqflite: ^2.0.2+1
  path: ^1.8.3
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
